import { writeFileSync, mkdirSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { buildAllMatches } from "../src/mappers/matches.ts"

/** Keep in sync with app.config.ts tournament.id */
const TOURNAMENT_ID = "world-cup-2026"

const scriptDir = dirname(fileURLToPath(import.meta.url))
const rootDir = join(scriptDir, "..")
const outPath = join(rootDir, "supabase/seed/world-cup-2026-match-results.sql")

const matches = buildAllMatches()
const values = matches
  .map(
    (m) =>
      `  ('${TOURNAMENT_ID}', '${m.id}', null, null)`,
  )
  .join(",\n")

const sql = `-- Generated by scripts/generate-supabase-seed.ts — do not edit by hand
-- Re-run: npx tsx scripts/generate-supabase-seed.ts
-- Matches: ${matches.length}

insert into public.match_results (tournament_id, match_id, home, away) values
${values}
on conflict (tournament_id, match_id) do nothing;
`

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, sql, "utf8")

console.log(`Wrote ${matches.length} match rows to ${outPath}`)
